project/project/urls.py
from django.contrib import admin
from django.urls import path
from yt_app.views import (
        Index, 
        AddTournamentView,
        AddPlaceView, 
        AddGameView, 
        AddTeamView, 
        AddMatchView, 
        AddDuelView, 
        ListTournaments, 
        ViewTeams, 
        UpdateTeam, 
        TeamDetail,
        ViewDuel,
        UpdateDuel,
        )
from acc.views import LogInView, LogOutView, RegisterView 

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', Index.as_view(), name='index'),
    path('add_tournament', AddTournamentView.as_view(), name='add_tournament'),
    path('add_place', AddPlaceView.as_view(), name='add_place'),
    path('add_game', AddGameView.as_view(), name='add_game'),
    path('add_team', AddTeamView.as_view(), name='add_team'),
    path('add_match', AddMatchView.as_view(), name='add_match'),
    path('add_duel', AddDuelView.as_view(), name='add_duel'),
    path('list_tournaments', ListTournaments.as_view(), name='list_tournaments'),
    path('view_teams', ViewTeams.as_view(), name='view_teams'),
    path('update_team', UpdateTeam.as_view(), name='update_team'),
    path('detail_team/<int:id>/', TeamDetail.as_view(), name='detail_team'),
    path('view_duel', ViewDuel.as_view(), name='view_duel'),
    path('update_duel/<int:pk>/', UpdateDuel.as_view(), name='update_duel'),
    path('login', LogInView.as_view(), name='login'),
    path('logout', LogOutView.as_view(), name='logout'),
    path('register', RegisterView.as_view(), name='register'),
]

project/yt_app/models.py
from django.db import models
from django.contrib.auth.models import User

# Create your models here.

class Place(models.Model):
    name = models.CharField(max_length=30)
    description = models.CharField(max_length=500)
    address = models.CharField(max_length=300)

    def __str__(self):
        return self.name


class Game(models.Model):  
    G_TYPES = (
        (1, "RTS"),
        (2, "FPS"),
        (3, "MOBA"),
        (4, "Other"),
    )
    game_type = models.IntegerField(choices=G_TYPES)
    name = models.CharField(max_length=30)
    description = models.CharField(max_length=500)
    created = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return self.name


class Tournament(models.Model):
    name = models.CharField(max_length=30)
    description = models.CharField(max_length=500)
    created = models.DateTimeField(auto_now_add=True)
    place = models.ManyToManyField(Place)
    game = models.ManyToManyField(Game)

    def __str__(self):
        return self.name



class Team(models.Model):
    name = models.CharField(max_length=30)
    tournaments = models.ManyToManyField(Tournament, null=True)
    players = models.ManyToManyField(User)

    def __str__(self):
        return self.name

    def get_update_url(self):
        return f'/detail_team/{self.id}/'

class Match(models.Model):
    name = models.CharField(max_length=30)
    created = models.DateTimeField(auto_now_add=True)
    team1 = models.ForeignKey(Team, related_name="team1", on_delete=models.CASCADE, default=None)
    team2 = models.ForeignKey(Team, on_delete=models.CASCADE, default=None)
    tournament = models.ForeignKey(Tournament, on_delete=models.CASCADE)

    def __str__(self):
        return self.name


class Duel(models.Model):
    name = models.CharField(max_length=30)
    created = models.DateTimeField(auto_now_add=True)
    match_field = models.ForeignKey(Match, on_delete=models.CASCADE)
    winner = models.ForeignKey(Team, on_delete=models.CASCADE, null=True)

    def get_teams(self):
        return [self.match_field.team1, self.match_field.team2]

    def __str__(self):
        return self.name

    def get_update_url(self):
        return f'/update_duel/{self.id}/'

project/templates/bar.html
<div class="topnav" id='myTopNav'>
    <a href="{% url 'index' %}">Home page</a>
    <a href="{% url 'list_tournaments' %}">List Tournaments</a>
    {% if user.is_superuser%}
        <a href="{% url 'add_place' %}">Add place</a>
        <a href="{% url 'add_game' %}">Add game</a>
        <a href="{% url 'add_tournament' %}">Add tournament</a>
        <a href="{% url 'add_team' %}">Add team</a>
        <a href="{% url 'add_match' %}">Add match</a>
        <a href="{% url 'add_duel' %}">Add duel</a>
        <a href="{% url 'view_teams' %}">View teams</a>
        <a href="{% url 'update_team' %}">Update team</a>
        <a href="{% url 'view_duel' %}">View duels</a>
        <a href="{% url 'logout' %}">Log out</a>
    {% elif user.is_authenticated %}
        <a href="{% url 'add_tournament' %}">Add tournament</a>
        <a href="{% url 'add_team' %}">Add team</a>
        <a href="{% url 'add_match' %}">Add match</a>
        <a href="{% url 'add_duel' %}">Add duel</a>
        <a href="{% url 'view_teams' %}">View teams</a>
        <a href="{% url 'update_team' %}">Update team</a>
        <a href="{% url 'view_duel' %}">View duels</a>
        <a href="{% url 'logout' %}">Log out</a>
    {% else %}
        <a href="{% url 'login' %}">Log in</a>
        <a href="{% url 'register' %}">Register</a>
    {% endif %}
</div>

project/templates/base.html
<!doctype html>
{% load static %}
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport"
          content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    {% block title %}
    <title>Document</title>
    {% endblock %}
    <link rel="stylesheet" type="text/css" href="{% static 'base.css' %}">
</head>
<body>
{% include 'bar.html' %}

{% block content %}
        
{% endblock %}

<p>{% if user.is_authenticated %}
Log as: {{ user.username }}
{% endif %}
</div>
</body>
</html>

project/templates/duel_list.html
{% extends 'base.html' %}
{% block content %}

    {% for match in matches %}
    <ul> {{ match.name }}
        {% for duel in match.duel_set.all %}
        <li>
            <a href="{{ duel.get_update_url }}">{{ duel }}</a>
            Winner: {{ duel.winner }}
        </li>
        {% endfor %}

    </ul>
    {% endfor %}

{% endblock %}

project/templates/form.html
{% extends 'base.html' %}
{% block content %}
    <form method="post">
     {% csrf_token %}
    {{ form.as_p }}
    <input type="submit">
    </form>
{% endblock %}

project/templates/index.html
{% extends 'base.html' %}
{% block content %}
    Welcome to Your-Tournament
{% endblock %}

project/templates/obj_list_url.html
{% extends 'base.html' %}
{% block content %}

    <ul>
    {% for obj in object_list %}
        <li>
            <a href="{{ obj.get_update_url }}">{{ obj }}</a>
        </li>

    {% endfor %}
    </ul>

{% endblock %}

project/templates/team.html
{% extends 'base.html' %}
{% block content %}
    Team name: {{ team.name }}
    <p>
    <ul>Tournaments
        {% for tournament in tournaments %}
        <li>{{ tournament }}</li>
        {% endfor %}
    </ul>
    <ul> Players
        {% for player in players %}
        <li>{{ player}}</li>
        {% endfor %}
    </ul>
{% endblock %}

project/templates/tournament_list.html
{% extends 'base.html' %}
{% block content %}
<title>Tournament list</title>
    {% for tournament in object_list %}
        <li>{{ tournament }}</li>
    {% endfor %}
{% endblock %}

project/templates/update_duel.html
{% extends 'base.html' %}
{% block content %}
<form action="" method="post">
    {% csrf_token %}
    {{ form.as_p }}
    <input type="submit" value="Save">
</form>
{% endblock %}